### ISSUE TITLE
API error: access forbidden

### ISSUE THREAD

**Issue by PintjesB** [Teifun2/cs-unifi-bouncer#36]
When using an API key for Unifi it keeps giving this error:

```
unifi-bouncer  | 2025-04-09T13:46:06.267817736Z INFO Initializing new UniFi client                
unifi-bouncer  | 2025-04-09T13:46:06.380207060Z {"level":"info","time":"2025-04-09T15:46:06+02:00","message":"Zone Based Firewall: true"}
unifi-bouncer  | 2025-04-09T13:46:06.665014989Z {"level":"info","time":"2025-04-09T15:46:06+02:00","message":"Unifi Connection Initialized"}
unifi-bouncer  | 2025-04-09T13:46:06.665459153Z {"level":"debug","time":"2025-04-09T15:46:06+02:00","message":"Processing new and deleted decisions . . ."}
unifi-bouncer  | 2025-04-09T13:46:06.686445662Z time="2025-04-09T15:46:06+02:00" level=error msg="API error: access forbidden"
unifi-bouncer  | 2025-04-09T13:46:06.688925004Z panic: runtime error: invalid memory address or nil pointer dereference
unifi-bouncer  | 2025-04-09T13:46:06.688963011Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa6849c]
unifi-bouncer  | 2025-04-09T13:46:06.688980733Z 
unifi-bouncer  | 2025-04-09T13:46:06.688996262Z goroutine 36 [running]:
unifi-bouncer  | 2025-04-09T13:46:06.689011826Z main.(*unifiAddrList).decisionProcess(0xc00061ef00, 0x0)
unifi-bouncer  | 2025-04-09T13:46:06.689027374Z 	github.com/teifun2/cs-unifi-bouncer/unifi.go:355 +0x1c
unifi-bouncer  | 2025-04-09T13:46:06.689043390Z main.main.func2()
unifi-bouncer  | 2025-04-09T13:46:06.689058851Z 	github.com/teifun2/cs-unifi-bouncer/main.go:90 +0x125
unifi-bouncer  | 2025-04-09T13:46:06.689101037Z golang.org/x/sync/errgroup.(*Group).Go.func1()
unifi-bouncer  | 2025-04-09T13:46:06.689185610Z 	golang.org/x/sync@v0.12.0/errgroup/errgroup.go:78 +0x50
unifi-bouncer  | 2025-04-09T13:46:06.689213267Z created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
unifi-bouncer  | 2025-04-09T13:46:06.689230016Z 	golang.org/x/sync@v0.12.0/errgroup/errgroup.go:75 +0x93
```

Docker-compose:
```
  unifi-bouncer:
    image: ghcr.io/teifun2/cs-unifi-bouncer:v1.1.1
    container_name: unifi-bouncer
    restart: unless-stopped
    environment:
      TZ: Europe/Brussels
      LOG_LEVEL: 0 # 0=debug, 1=info, 2=warn, 3=error
      UNIFI_LOGGING: true
      CROWDSEC_BOUNCER_API_KEY: ${CROWDSEC_BOUNCER_API_KEY}
      CROWDSEC_URL: ${CROWDSEC_URL}
      UNIFI_HOST: ${UNIFI_HOST}
      UNIFI_API_KEY: ${UNIFI_API_KEY}
      UNIFI_IPV6: false
      UNIFI_SKIP_TLS_VERIFY: true
```
