### ISSUE TITLE
Container fails to start

### ISSUE THREAD

**Issue by stuartb55** [Teifun2/cs-unifi-bouncer#43]
Container fails to start with this error:

```
goroutine 50 [running]:
main.(*unifiAddrList).decisionProcess(0x4000412500, 0x0)
        github.com/teifun2/cs-unifi-bouncer/unifi.go:355 +0x20
main.main.func2()
        github.com/teifun2/cs-unifi-bouncer/main.go:90 +0xf0
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.12.0/errgroup/errgroup.go:78 +0x54
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
        golang.org/x/sync@v0.12.0/errgroup/errgroup.go:75 +0x94
{"level":"info","time":"2025-05-19T12:15:37+01:00","message":"Starting cs-unifi-bouncer with version: v1.1.1"}
time="2025-05-19T12:15:37+01:00" level=info msg="Using API key auth"
{"level":"info","time":"2025-05-19T12:15:37+01:00","message":"Connecting to unifi"}
INFO Initializing new UniFi client
{"level":"info","time":"2025-05-19T12:15:37+01:00","message":"Zone Based Firewall: true"}
{"level":"info","time":"2025-05-19T12:15:37+01:00","message":"Unifi Connection Initialized"}
{"level":"debug","time":"2025-05-19T12:15:37+01:00","message":"Processing new and deleted decisions . . ."}
time="2025-05-19T12:15:37+01:00" level=error msg="API error: access forbidden"
{"level":"error","error":"bouncer stream halted","time":"2025-05-19T12:15:37+01:00"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5f7900]
```

docker compose:

```
crowdsec:
    image: crowdsecurity/crowdsec
    container_name: crowdsec
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8081:8080" # API

  cs-unifi-bouncer:
    image: ghcr.io/teifun2/cs-unifi-bouncer
    container_name: cs-unifi-bouncer
    restart: unless-stopped
    depends_on:
      - crowdsec
    environment:
      - TZ=Europe/London
      - CROWDSEC_URL=http://192.168.1.11:8081
      - CROWDSEC_BOUNCER_API_KEY=Wh...vM
      - UNIFI_HOST=https://192.168.1.1
      - UNIFI_API_KEY=nO81Plrw8ltlH0UWdlbsuhqMlU1cwEBG
      - UNIFI_SKIP_TLS_VERIFY=true
      - LOG_LEVEL=-1
```

Unifi user has full admin permissions on Network and Control Plane.
