### ISSUE TITLE
Can't authenticate with UCG Fibre

### ISSUE THREAD

**Issue by BKOmega** [Teifun2/cs-unifi-bouncer#44]
In docker compose I've tried all combinations of username, password and api and get similar error message each time. 

Username, password and api
failed validating client configuration: validation failed: \nClientConfig.User: User is an excluded field\nClientConfig.Password: Password is an excluded field
Api
failed validating client configuration: validation failed: \nClientConfig.User: User is a required field\nClientConfig.Password: Password is an excluded field
Username and api
failed validating client configuration: validation failed: \nClientConfig.User: User is an excluded field\nClientConfig.Password: Password is an excluded field
Username and password
failed validating client configuration: validation failed: \nClientConfig.User: User is an excluded field\nClientConfig.Password: Password is an excluded field

What am I doing wrong? Device version is 4.2.12 if that has anything to do with it?

**Comment by stuartb55** [comment]
Assuming your using an API key for your Unifi user. This is in my docker-compose.yml which is working:

```
crowdsec:
    image: crowdsecurity/crowdsec
    container_name: crowdsec
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /Users/stuart/crowdsec:/etc/crowdsec
    ports:
      - "8081:8080" # API

  cs-unifi-bouncer:
    image: ghcr.io/teifun2/cs-unifi-bouncer
    container_name: cs-unifi-bouncer
    restart: unless-stopped
    depends_on:
      - crowdsec
    environment:
      - TZ=Europe/London
      - CROWDSEC_URL=http://192.168.1.11:8081
      - CROWDSEC_BOUNCER_API_KEY=n9...Py4
      - UNIFI_HOST=https://192.168.1.1
      - UNIFI_API_KEY=1Y...sd
      - UNIFI_SKIP_TLS_VERIFY=true
      - LOG_LEVEL=-1
```
